import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// =============================================
// PROVIDER DATA (AMCs)
// =============================================

const PROVIDERS = [
  { id: 'AMC-HDFC', name: 'HDFC Asset Management Company', shortName: 'HDFC MF', sebiRegNo: 'INP000000506' },
  { id: 'AMC-ICICI', name: 'ICICI Prudential Asset Management Company', shortName: 'ICICI Pru MF', sebiRegNo: 'INP000000517' },
  { id: 'AMC-SBI', name: 'SBI Funds Management', shortName: 'SBI MF', sebiRegNo: 'INP000000316' },
  { id: 'AMC-AXIS', name: 'Axis Asset Management Company', shortName: 'Axis MF', sebiRegNo: 'INP000000426' },
  { id: 'AMC-KOTAK', name: 'Kotak Mahindra Asset Management Company', shortName: 'Kotak MF', sebiRegNo: 'INP000000458' },
  { id: 'AMC-NIPPON', name: 'Nippon Life India Asset Management', shortName: 'Nippon India MF', sebiRegNo: 'INP000000286' },
  { id: 'AMC-MIRAE', name: 'Mirae Asset Investment Managers', shortName: 'Mirae Asset MF', sebiRegNo: 'INP000000412' },
  { id: 'AMC-PPFAS', name: 'PPFAS Asset Management', shortName: 'Parag Parikh MF', sebiRegNo: 'INP000000475' },
  { id: 'AMC-UTI', name: 'UTI Asset Management Company', shortName: 'UTI MF', sebiRegNo: 'INP000000336' },
  { id: 'AMC-DSP', name: 'DSP Investment Managers', shortName: 'DSP MF', sebiRegNo: 'INP000000374' },
  { id: 'AMC-ABSL', name: 'Aditya Birla Sun Life AMC', shortName: 'ABSL MF', sebiRegNo: 'INP000000262' },
  { id: 'AMC-TATA', name: 'Tata Asset Management', shortName: 'Tata MF', sebiRegNo: 'INP000000266' },
  { id: 'AMC-FRANKLIN', name: 'Franklin Templeton Asset Management India', shortName: 'Franklin MF', sebiRegNo: 'INP000000363' },
  { id: 'AMC-MOTILAL', name: 'Motilal Oswal Asset Management Company', shortName: 'Motilal Oswal MF', sebiRegNo: 'INP000000509' },
  { id: 'AMC-QUANT', name: 'Quant Money Managers', shortName: 'Quant MF', sebiRegNo: 'INP000000398' },
];

// =============================================
// SCHEME DATA
// =============================================

interface SchemeData {
  id: string;
  providerId: string;
  name: string;
  categoryId: string;
  subCategory: string;
  benchmark: string;
  fundManager: string;
  investmentObjective: string;
  exitLoad: string;
  mfapiSchemeCode?: number;
  plans: PlanData[];
}

interface PlanData {
  id: string;
  isin: string;
  rtaIdentifier: string;
  amfiIdentifier?: string;
  name: string;
  plan: 'direct' | 'regular';
  option: 'growth' | 'idcw_payout' | 'idcw_reinvestment';
  mfapiSchemeCode: number;
  // NAV and metrics
  nav: number;
  dayChange: number;
  return1m: number;
  return3m: number;
  return6m: number;
  return1y: number;
  return3y: number;
  return5y: number;
  riskRating: number;
  fundRating: number;
  expenseRatio: number;
  aum: number; // In Crores
  volatility: number;
  sharpeRatio: number;
}

const SCHEMES: SchemeData[] = [
  // =============================================
  // LARGE CAP FUNDS (8 schemes)
  // =============================================
  {
    id: 'SCH-AXIS-BLUE',
    providerId: 'AMC-AXIS',
    name: 'Axis Bluechip Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'NIFTY 50 TRI',
    fundManager: 'Shreyash Devalkar',
    investmentObjective: 'To achieve long term capital growth by investing in a diversified portfolio predominantly consisting of equity & equity related instruments of large cap companies.',
    exitLoad: '0.5% if redeemed within 90 days',
    mfapiSchemeCode: 120503,
    plans: [
      {
        id: 'PLAN-AXIS-BLUE-DG',
        isin: 'INF846K01DP8',
        rtaIdentifier: 'AXISBLUDG',
        amfiIdentifier: '120503',
        name: 'Axis Bluechip Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120503,
        nav: 52.34,
        dayChange: 0.45,
        return1m: 2.1,
        return3m: 5.8,
        return6m: 12.4,
        return1y: 18.5,
        return3y: 15.2,
        return5y: 16.8,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.58,
        aum: 34567,
        volatility: 14.2,
        sharpeRatio: 1.12,
      },
      {
        id: 'PLAN-AXIS-BLUE-RG',
        isin: 'INF846K01EQ6',
        rtaIdentifier: 'AXISBLURG',
        amfiIdentifier: '112277',
        name: 'Axis Bluechip Fund - Regular Plan - Growth',
        plan: 'regular',
        option: 'growth',
        mfapiSchemeCode: 112277,
        nav: 48.92,
        dayChange: 0.42,
        return1m: 1.9,
        return3m: 5.5,
        return6m: 11.8,
        return1y: 17.2,
        return3y: 13.8,
        return5y: 15.1,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 1.68,
        aum: 34567,
        volatility: 14.2,
        sharpeRatio: 0.98,
      },
    ],
  },
  {
    id: 'SCH-MIRAE-LC',
    providerId: 'AMC-MIRAE',
    name: 'Mirae Asset Large Cap Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'NIFTY 100 TRI',
    fundManager: 'Gaurav Misra',
    investmentObjective: 'To generate long term capital appreciation from a diversified portfolio that is predominantly invested in equity and equity related securities of large cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 119598,
    plans: [
      {
        id: 'PLAN-MIRAE-LC-DG',
        isin: 'INF769K01EH7',
        rtaIdentifier: 'MIRAELCDG',
        name: 'Mirae Asset Large Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119598,
        nav: 98.67,
        dayChange: 0.78,
        return1m: 2.3,
        return3m: 6.2,
        return6m: 13.1,
        return1y: 20.2,
        return3y: 16.8,
        return5y: 17.5,
        riskRating: 4,
        fundRating: 5,
        expenseRatio: 0.52,
        aum: 42890,
        volatility: 13.8,
        sharpeRatio: 1.24,
      },
    ],
  },
  {
    id: 'SCH-SBI-BLUE',
    providerId: 'AMC-SBI',
    name: 'SBI Bluechip Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'S&P BSE 100 TRI',
    fundManager: 'Sohini Andani',
    investmentObjective: 'To provide investors with opportunities for long-term growth in capital through an active management of investments in a diversified basket of equity stocks of large cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 119600,
    plans: [
      {
        id: 'PLAN-SBI-BLUE-DG',
        isin: 'INF200K01PP9',
        rtaIdentifier: 'SBIBLUDG',
        name: 'SBI Bluechip Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119600,
        nav: 78.45,
        dayChange: 0.62,
        return1m: 1.8,
        return3m: 5.4,
        return6m: 11.9,
        return1y: 16.8,
        return3y: 14.5,
        return5y: 15.9,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.88,
        aum: 38765,
        volatility: 13.5,
        sharpeRatio: 1.08,
      },
    ],
  },
  {
    id: 'SCH-ICICI-BLUE',
    providerId: 'AMC-ICICI',
    name: 'ICICI Prudential Bluechip Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'NIFTY 100 TRI',
    fundManager: 'Anish Tawakley',
    investmentObjective: 'To generate long-term capital appreciation and income distribution to unit holders from a portfolio that is predominantly invested in equity and equity related securities of large cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120594,
    plans: [
      {
        id: 'PLAN-ICICI-BLUE-DG',
        isin: 'INF109K01Y38',
        rtaIdentifier: 'ICICIBLDG',
        name: 'ICICI Prudential Bluechip Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120594,
        nav: 92.30,
        dayChange: 0.71,
        return1m: 2.0,
        return3m: 5.9,
        return6m: 12.8,
        return1y: 19.1,
        return3y: 15.9,
        return5y: 16.2,
        riskRating: 4,
        fundRating: 5,
        expenseRatio: 1.04,
        aum: 51234,
        volatility: 13.9,
        sharpeRatio: 1.18,
      },
    ],
  },
  {
    id: 'SCH-HDFC-TOP100',
    providerId: 'AMC-HDFC',
    name: 'HDFC Top 100 Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'NIFTY 100 TRI',
    fundManager: 'Rahul Baijal',
    investmentObjective: 'To generate long-term capital appreciation from a portfolio that is predominantly invested in Large Cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 118485,
    plans: [
      {
        id: 'PLAN-HDFC-TOP100-DG',
        isin: 'INF179K01WL6',
        rtaIdentifier: 'HDFCT100DG',
        name: 'HDFC Top 100 Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118485,
        nav: 1025.45,
        dayChange: 8.12,
        return1m: 1.9,
        return3m: 5.6,
        return6m: 12.2,
        return1y: 17.8,
        return3y: 15.1,
        return5y: 15.6,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 1.12,
        aum: 29876,
        volatility: 14.0,
        sharpeRatio: 1.05,
      },
    ],
  },
  {
    id: 'SCH-KOTAK-BLUE',
    providerId: 'AMC-KOTAK',
    name: 'Kotak Bluechip Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'NIFTY 50 TRI',
    fundManager: 'Harsha Upadhyaya',
    investmentObjective: 'To generate long-term capital appreciation from a diversified portfolio of equity and equity related securities of large cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120535,
    plans: [
      {
        id: 'PLAN-KOTAK-BLUE-DG',
        isin: 'INF174K01FP2',
        rtaIdentifier: 'KOTAKBLDG',
        name: 'Kotak Bluechip Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120535,
        nav: 478.92,
        dayChange: 3.78,
        return1m: 2.2,
        return3m: 6.0,
        return6m: 12.9,
        return1y: 18.9,
        return3y: 15.6,
        return5y: 16.4,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.67,
        aum: 7234,
        volatility: 13.7,
        sharpeRatio: 1.15,
      },
    ],
  },
  {
    id: 'SCH-NIPPON-LC',
    providerId: 'AMC-NIPPON',
    name: 'Nippon India Large Cap Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'NIFTY 100 TRI',
    fundManager: 'Sailesh Raj Bhan',
    investmentObjective: 'To generate long term capital appreciation by investing predominantly in equity and equity related instruments of large cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 118668,
    plans: [
      {
        id: 'PLAN-NIPPON-LC-DG',
        isin: 'INF204K01SC5',
        rtaIdentifier: 'NIPPONLCDG',
        name: 'Nippon India Large Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118668,
        nav: 72.45,
        dayChange: 0.58,
        return1m: 1.7,
        return3m: 5.2,
        return6m: 11.5,
        return1y: 16.2,
        return3y: 14.0,
        return5y: 14.8,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.95,
        aum: 19876,
        volatility: 14.1,
        sharpeRatio: 1.02,
      },
    ],
  },
  {
    id: 'SCH-UTI-MASTERSHARE',
    providerId: 'AMC-UTI',
    name: 'UTI Mastershare Fund',
    categoryId: 'L3-LARGE_CAP',
    subCategory: 'Large Cap',
    benchmark: 'S&P BSE 100 TRI',
    fundManager: 'Swati Kulkarni',
    investmentObjective: 'To generate long term capital appreciation from a diversified portfolio of equity and equity related instruments of large cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120556,
    plans: [
      {
        id: 'PLAN-UTI-MASTER-DG',
        isin: 'INF789F01YB5',
        rtaIdentifier: 'UTIMASTDG',
        name: 'UTI Mastershare Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120556,
        nav: 245.67,
        dayChange: 1.92,
        return1m: 1.6,
        return3m: 5.0,
        return6m: 11.2,
        return1y: 15.8,
        return3y: 13.5,
        return5y: 14.2,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 1.05,
        aum: 12456,
        volatility: 13.6,
        sharpeRatio: 0.98,
      },
    ],
  },

  // =============================================
  // FLEXI CAP FUNDS (6 schemes)
  // =============================================
  {
    id: 'SCH-PPFAS-FLEXI',
    providerId: 'AMC-PPFAS',
    name: 'Parag Parikh Flexi Cap Fund',
    categoryId: 'L3-FLEXI_CAP',
    subCategory: 'Flexi Cap',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Rajeev Thakkar',
    investmentObjective: 'To generate long-term capital growth from an actively managed portfolio of equity & equity related securities in Indian and foreign markets.',
    exitLoad: '2% if redeemed within 365 days, 1% if redeemed between 365-730 days',
    mfapiSchemeCode: 125497,
    plans: [
      {
        id: 'PLAN-PPFAS-FLEXI-DG',
        isin: 'INF879O01019',
        rtaIdentifier: 'PPFASFLXDG',
        name: 'Parag Parikh Flexi Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 125497,
        nav: 68.45,
        dayChange: 0.52,
        return1m: 2.5,
        return3m: 6.8,
        return6m: 14.2,
        return1y: 22.5,
        return3y: 18.5,
        return5y: 19.2,
        riskRating: 4,
        fundRating: 5,
        expenseRatio: 0.63,
        aum: 65432,
        volatility: 12.8,
        sharpeRatio: 1.42,
      },
    ],
  },
  {
    id: 'SCH-HDFC-FLEXI',
    providerId: 'AMC-HDFC',
    name: 'HDFC Flexi Cap Fund',
    categoryId: 'L3-FLEXI_CAP',
    subCategory: 'Flexi Cap',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Roshi Jain',
    investmentObjective: 'To generate capital appreciation/income from a portfolio predominantly invested in equity and equity related instruments.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 122639,
    plans: [
      {
        id: 'PLAN-HDFC-FLEXI-DG',
        isin: 'INF179K01WG6',
        rtaIdentifier: 'HDFCFLXDG',
        name: 'HDFC Flexi Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 122639,
        nav: 41.23,
        dayChange: 0.32,
        return1m: 1.8,
        return3m: 5.5,
        return6m: 12.1,
        return1y: 17.5,
        return3y: 14.8,
        return5y: 15.4,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.80,
        aum: 48765,
        volatility: 14.5,
        sharpeRatio: 1.08,
      },
    ],
  },
  {
    id: 'SCH-QUANT-FLEXI',
    providerId: 'AMC-QUANT',
    name: 'Quant Flexi Cap Fund',
    categoryId: 'L3-FLEXI_CAP',
    subCategory: 'Flexi Cap',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Sanjeev Sharma',
    investmentObjective: 'To achieve long term capital appreciation by investing in equity and equity related instruments across market capitalization.',
    exitLoad: '1% if redeemed within 15 days',
    mfapiSchemeCode: 120843,
    plans: [
      {
        id: 'PLAN-QUANT-FLEXI-DG',
        isin: 'INF966L01598',
        rtaIdentifier: 'QUANTFLXDG',
        name: 'Quant Flexi Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120843,
        nav: 89.56,
        dayChange: 0.78,
        return1m: 3.2,
        return3m: 8.5,
        return6m: 18.2,
        return1y: 28.5,
        return3y: 22.8,
        return5y: 24.5,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.58,
        aum: 5678,
        volatility: 18.2,
        sharpeRatio: 1.38,
      },
    ],
  },
  {
    id: 'SCH-UTI-FLEXI',
    providerId: 'AMC-UTI',
    name: 'UTI Flexi Cap Fund',
    categoryId: 'L3-FLEXI_CAP',
    subCategory: 'Flexi Cap',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Ajay Tyagi',
    investmentObjective: 'To achieve long term capital appreciation by investing in a diversified portfolio of equity and equity related instruments.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120539,
    plans: [
      {
        id: 'PLAN-UTI-FLEXI-DG',
        isin: 'INF789F01EN4',
        rtaIdentifier: 'UTIFLXDG',
        name: 'UTI Flexi Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120539,
        nav: 312.78,
        dayChange: 2.45,
        return1m: 2.1,
        return3m: 6.0,
        return6m: 13.5,
        return1y: 19.8,
        return3y: 16.2,
        return5y: 17.1,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.92,
        aum: 28765,
        volatility: 14.8,
        sharpeRatio: 1.15,
      },
    ],
  },
  {
    id: 'SCH-KOTAK-FLEXI',
    providerId: 'AMC-KOTAK',
    name: 'Kotak Flexi Cap Fund',
    categoryId: 'L3-FLEXI_CAP',
    subCategory: 'Flexi Cap',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Harsha Upadhyaya',
    investmentObjective: 'To generate long-term capital appreciation from a diversified portfolio of equity and equity related securities.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120534,
    plans: [
      {
        id: 'PLAN-KOTAK-FLEXI-DG',
        isin: 'INF174K01FJ5',
        rtaIdentifier: 'KOTAKFLXDG',
        name: 'Kotak Flexi Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120534,
        nav: 67.89,
        dayChange: 0.52,
        return1m: 2.0,
        return3m: 5.8,
        return6m: 12.8,
        return1y: 18.2,
        return3y: 15.5,
        return5y: 16.2,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.59,
        aum: 42567,
        volatility: 14.2,
        sharpeRatio: 1.12,
      },
    ],
  },
  {
    id: 'SCH-AXIS-FLEXI',
    providerId: 'AMC-AXIS',
    name: 'Axis Flexi Cap Fund',
    categoryId: 'L3-FLEXI_CAP',
    subCategory: 'Flexi Cap',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Jinesh Gopani',
    investmentObjective: 'To achieve long term capital appreciation by investing in equity and equity related instruments across market capitalization.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 143665,
    plans: [
      {
        id: 'PLAN-AXIS-FLEXI-DG',
        isin: 'INF846K01M05',
        rtaIdentifier: 'AXISFLXDG',
        name: 'Axis Flexi Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 143665,
        nav: 21.45,
        dayChange: 0.18,
        return1m: 1.9,
        return3m: 5.6,
        return6m: 12.4,
        return1y: 17.8,
        return3y: 14.9,
        return5y: 15.8,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.52,
        aum: 12345,
        volatility: 14.0,
        sharpeRatio: 1.10,
      },
    ],
  },

  // =============================================
  // MID CAP FUNDS (5 schemes)
  // =============================================
  {
    id: 'SCH-HDFC-MIDCAP',
    providerId: 'AMC-HDFC',
    name: 'HDFC Mid-Cap Opportunities Fund',
    categoryId: 'L3-MID_CAP',
    subCategory: 'Mid Cap',
    benchmark: 'NIFTY Midcap 150 TRI',
    fundManager: 'Chirag Setalvad',
    investmentObjective: 'To generate long term capital appreciation from a portfolio that is substantially constituted of equity and equity related securities of mid cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 118989,
    plans: [
      {
        id: 'PLAN-HDFC-MIDCAP-DG',
        isin: 'INF179K01WH4',
        rtaIdentifier: 'HDFCMIDDG',
        name: 'HDFC Mid-Cap Opportunities Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118989,
        nav: 165.78,
        dayChange: 1.45,
        return1m: 2.8,
        return3m: 7.5,
        return6m: 15.8,
        return1y: 24.5,
        return3y: 20.2,
        return5y: 21.5,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.87,
        aum: 56789,
        volatility: 16.5,
        sharpeRatio: 1.28,
      },
    ],
  },
  {
    id: 'SCH-KOTAK-EMERG',
    providerId: 'AMC-KOTAK',
    name: 'Kotak Emerging Equity Fund',
    categoryId: 'L3-MID_CAP',
    subCategory: 'Mid Cap',
    benchmark: 'NIFTY Midcap 150 TRI',
    fundManager: 'Pankaj Tibrewal',
    investmentObjective: 'To generate long-term capital appreciation from a diversified portfolio of equity and equity related securities of mid cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120505,
    plans: [
      {
        id: 'PLAN-KOTAK-EMERG-DG',
        isin: 'INF174K01FL1',
        rtaIdentifier: 'KOTAKEMRDG',
        name: 'Kotak Emerging Equity Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120505,
        nav: 95.67,
        dayChange: 0.82,
        return1m: 2.6,
        return3m: 7.2,
        return6m: 15.2,
        return1y: 23.8,
        return3y: 19.5,
        return5y: 20.8,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.54,
        aum: 38765,
        volatility: 16.2,
        sharpeRatio: 1.25,
      },
    ],
  },
  {
    id: 'SCH-AXIS-MIDCAP',
    providerId: 'AMC-AXIS',
    name: 'Axis Midcap Fund',
    categoryId: 'L3-MID_CAP',
    subCategory: 'Mid Cap',
    benchmark: 'NIFTY Midcap 150 TRI',
    fundManager: 'Shreyash Devalkar',
    investmentObjective: 'To achieve long term capital appreciation by investing in a diversified portfolio predominantly consisting of equity and equity related instruments of mid cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 119062,
    plans: [
      {
        id: 'PLAN-AXIS-MIDCAP-DG',
        isin: 'INF846K01DQ6',
        rtaIdentifier: 'AXISMIDDG',
        name: 'Axis Midcap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119062,
        nav: 89.34,
        dayChange: 0.76,
        return1m: 2.4,
        return3m: 6.8,
        return6m: 14.5,
        return1y: 22.2,
        return3y: 18.5,
        return5y: 19.8,
        riskRating: 5,
        fundRating: 4,
        expenseRatio: 0.48,
        aum: 24567,
        volatility: 15.8,
        sharpeRatio: 1.22,
      },
    ],
  },
  {
    id: 'SCH-DSP-MIDCAP',
    providerId: 'AMC-DSP',
    name: 'DSP Midcap Fund',
    categoryId: 'L3-MID_CAP',
    subCategory: 'Mid Cap',
    benchmark: 'NIFTY Midcap 150 TRI',
    fundManager: 'Vinit Sambre',
    investmentObjective: 'To generate long term capital appreciation from a portfolio that is substantially constituted of equity and equity related securities of mid cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 119008,
    plans: [
      {
        id: 'PLAN-DSP-MIDCAP-DG',
        isin: 'INF740K01QN7',
        rtaIdentifier: 'DSPMIDDG',
        name: 'DSP Midcap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119008,
        nav: 145.67,
        dayChange: 1.25,
        return1m: 2.5,
        return3m: 7.0,
        return6m: 14.8,
        return1y: 22.8,
        return3y: 18.8,
        return5y: 20.2,
        riskRating: 5,
        fundRating: 4,
        expenseRatio: 0.75,
        aum: 18765,
        volatility: 16.0,
        sharpeRatio: 1.20,
      },
    ],
  },
  {
    id: 'SCH-NIPPON-GROWTH',
    providerId: 'AMC-NIPPON',
    name: 'Nippon India Growth Fund',
    categoryId: 'L3-MID_CAP',
    subCategory: 'Mid Cap',
    benchmark: 'NIFTY Midcap 150 TRI',
    fundManager: 'Manish Gunwani',
    investmentObjective: 'To generate long term capital appreciation by investing predominantly in equity and equity related instruments of mid cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 118617,
    plans: [
      {
        id: 'PLAN-NIPPON-GROWTH-DG',
        isin: 'INF204K01QU7',
        rtaIdentifier: 'NIPPONGRDG',
        name: 'Nippon India Growth Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118617,
        nav: 3456.78,
        dayChange: 28.45,
        return1m: 2.7,
        return3m: 7.3,
        return6m: 15.5,
        return1y: 24.0,
        return3y: 19.8,
        return5y: 21.2,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.92,
        aum: 22345,
        volatility: 16.4,
        sharpeRatio: 1.26,
      },
    ],
  },

  // =============================================
  // SMALL CAP FUNDS (4 schemes)
  // =============================================
  {
    id: 'SCH-SBI-SMALL',
    providerId: 'AMC-SBI',
    name: 'SBI Small Cap Fund',
    categoryId: 'L3-SMALL_CAP',
    subCategory: 'Small Cap',
    benchmark: 'S&P BSE 250 Small Cap TRI',
    fundManager: 'R. Srinivasan',
    investmentObjective: 'To provide investors with opportunities for long-term growth in capital through an active management of investments in a diversified basket of equity stocks of small cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 125494,
    plans: [
      {
        id: 'PLAN-SBI-SMALL-DG',
        isin: 'INF200K01SM4',
        rtaIdentifier: 'SBISMALLDG',
        name: 'SBI Small Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 125494,
        nav: 165.78,
        dayChange: 1.56,
        return1m: 3.2,
        return3m: 8.5,
        return6m: 18.2,
        return1y: 28.5,
        return3y: 24.2,
        return5y: 26.5,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.68,
        aum: 28765,
        volatility: 18.5,
        sharpeRatio: 1.35,
      },
    ],
  },
  {
    id: 'SCH-NIPPON-SMALL',
    providerId: 'AMC-NIPPON',
    name: 'Nippon India Small Cap Fund',
    categoryId: 'L3-SMALL_CAP',
    subCategory: 'Small Cap',
    benchmark: 'S&P BSE 250 Small Cap TRI',
    fundManager: 'Samir Rachh',
    investmentObjective: 'To generate long term capital appreciation by investing predominantly in equity and equity related instruments of small cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 125354,
    plans: [
      {
        id: 'PLAN-NIPPON-SMALL-DG',
        isin: 'INF204K01V05',
        rtaIdentifier: 'NIPPONSMDG',
        name: 'Nippon India Small Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 125354,
        nav: 142.56,
        dayChange: 1.34,
        return1m: 3.5,
        return3m: 9.0,
        return6m: 19.5,
        return1y: 30.2,
        return3y: 25.8,
        return5y: 28.2,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.78,
        aum: 45678,
        volatility: 19.2,
        sharpeRatio: 1.42,
      },
    ],
  },
  {
    id: 'SCH-AXIS-SMALL',
    providerId: 'AMC-AXIS',
    name: 'Axis Small Cap Fund',
    categoryId: 'L3-SMALL_CAP',
    subCategory: 'Small Cap',
    benchmark: 'S&P BSE 250 Small Cap TRI',
    fundManager: 'Anupam Tiwari',
    investmentObjective: 'To achieve long term capital appreciation by investing in a diversified portfolio predominantly consisting of equity and equity related instruments of small cap companies.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 125356,
    plans: [
      {
        id: 'PLAN-AXIS-SMALL-DG',
        isin: 'INF846K01HX7',
        rtaIdentifier: 'AXISSMALLDG',
        name: 'Axis Small Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 125356,
        nav: 98.45,
        dayChange: 0.92,
        return1m: 3.0,
        return3m: 8.2,
        return6m: 17.5,
        return1y: 27.2,
        return3y: 22.8,
        return5y: 25.5,
        riskRating: 5,
        fundRating: 4,
        expenseRatio: 0.52,
        aum: 18765,
        volatility: 18.0,
        sharpeRatio: 1.32,
      },
    ],
  },
  {
    id: 'SCH-QUANT-SMALL',
    providerId: 'AMC-QUANT',
    name: 'Quant Small Cap Fund',
    categoryId: 'L3-SMALL_CAP',
    subCategory: 'Small Cap',
    benchmark: 'S&P BSE 250 Small Cap TRI',
    fundManager: 'Sanjeev Sharma',
    investmentObjective: 'To achieve long term capital appreciation by investing predominantly in equity and equity related instruments of small cap companies.',
    exitLoad: '1% if redeemed within 15 days',
    mfapiSchemeCode: 120839,
    plans: [
      {
        id: 'PLAN-QUANT-SMALL-DG',
        isin: 'INF966L01580',
        rtaIdentifier: 'QUANTSMDG',
        name: 'Quant Small Cap Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120839,
        nav: 245.67,
        dayChange: 2.45,
        return1m: 4.2,
        return3m: 10.5,
        return6m: 22.5,
        return1y: 35.8,
        return3y: 30.2,
        return5y: 32.5,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.62,
        aum: 8765,
        volatility: 22.5,
        sharpeRatio: 1.45,
      },
    ],
  },

  // =============================================
  // ELSS FUNDS (4 schemes)
  // =============================================
  {
    id: 'SCH-AXIS-ELSS',
    providerId: 'AMC-AXIS',
    name: 'Axis Long Term Equity Fund',
    categoryId: 'L3-ELSS',
    subCategory: 'ELSS',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Jinesh Gopani',
    investmentObjective: 'To generate long-term capital growth through equity investments along with income tax benefits.',
    exitLoad: 'Nil',
    lockinPeriod: 1095, // 3 years lock-in
    mfapiSchemeCode: 120716,
    plans: [
      {
        id: 'PLAN-AXIS-ELSS-DG',
        isin: 'INF846K01DR4',
        rtaIdentifier: 'AXISELSSDG',
        name: 'Axis Long Term Equity Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120716,
        nav: 78.45,
        dayChange: 0.62,
        return1m: 2.2,
        return3m: 6.2,
        return6m: 13.5,
        return1y: 20.5,
        return3y: 17.2,
        return5y: 18.5,
        riskRating: 4,
        fundRating: 5,
        expenseRatio: 0.56,
        aum: 35678,
        volatility: 14.5,
        sharpeRatio: 1.22,
      },
    ],
  },
  {
    id: 'SCH-MIRAE-ELSS',
    providerId: 'AMC-MIRAE',
    name: 'Mirae Asset Tax Saver Fund',
    categoryId: 'L3-ELSS',
    subCategory: 'ELSS',
    benchmark: 'NIFTY 200 TRI',
    fundManager: 'Neelesh Surana',
    investmentObjective: 'To generate long-term capital appreciation from a diversified portfolio of equity and equity related securities.',
    exitLoad: 'Nil',
    lockinPeriod: 1095,
    mfapiSchemeCode: 125494,
    plans: [
      {
        id: 'PLAN-MIRAE-ELSS-DG',
        isin: 'INF769K01GT9',
        rtaIdentifier: 'MIRAEELSSDG',
        name: 'Mirae Asset Tax Saver Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 125494,
        nav: 42.56,
        dayChange: 0.35,
        return1m: 2.4,
        return3m: 6.5,
        return6m: 14.0,
        return1y: 21.5,
        return3y: 18.0,
        return5y: 19.2,
        riskRating: 4,
        fundRating: 5,
        expenseRatio: 0.42,
        aum: 22345,
        volatility: 14.2,
        sharpeRatio: 1.28,
      },
    ],
  },
  {
    id: 'SCH-DSP-ELSS',
    providerId: 'AMC-DSP',
    name: 'DSP Tax Saver Fund',
    categoryId: 'L3-ELSS',
    subCategory: 'ELSS',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Rohit Singhania',
    investmentObjective: 'To generate medium to long-term capital appreciation from a diversified portfolio of equity and equity related securities.',
    exitLoad: 'Nil',
    lockinPeriod: 1095,
    mfapiSchemeCode: 118992,
    plans: [
      {
        id: 'PLAN-DSP-ELSS-DG',
        isin: 'INF740K01QO5',
        rtaIdentifier: 'DSPELSSDG',
        name: 'DSP Tax Saver Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118992,
        nav: 112.34,
        dayChange: 0.92,
        return1m: 2.1,
        return3m: 5.9,
        return6m: 12.8,
        return1y: 19.2,
        return3y: 16.5,
        return5y: 17.8,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.78,
        aum: 12456,
        volatility: 14.8,
        sharpeRatio: 1.15,
      },
    ],
  },
  {
    id: 'SCH-QUANT-ELSS',
    providerId: 'AMC-QUANT',
    name: 'Quant Tax Plan',
    categoryId: 'L3-ELSS',
    subCategory: 'ELSS',
    benchmark: 'NIFTY 500 TRI',
    fundManager: 'Sanjeev Sharma',
    investmentObjective: 'To generate long-term capital appreciation by investing in equity and equity related instruments.',
    exitLoad: 'Nil',
    lockinPeriod: 1095,
    mfapiSchemeCode: 120841,
    plans: [
      {
        id: 'PLAN-QUANT-ELSS-DG',
        isin: 'INF966L01572',
        rtaIdentifier: 'QUANTELSSDG',
        name: 'Quant Tax Plan - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120841,
        nav: 345.67,
        dayChange: 3.12,
        return1m: 3.5,
        return3m: 9.2,
        return6m: 19.5,
        return1y: 32.5,
        return3y: 26.8,
        return5y: 28.5,
        riskRating: 5,
        fundRating: 5,
        expenseRatio: 0.55,
        aum: 5678,
        volatility: 18.5,
        sharpeRatio: 1.52,
      },
    ],
  },

  // =============================================
  // DEBT FUNDS (6 schemes)
  // =============================================
  {
    id: 'SCH-SBI-LIQUID',
    providerId: 'AMC-SBI',
    name: 'SBI Liquid Fund',
    categoryId: 'L3-LIQUID',
    subCategory: 'Liquid',
    benchmark: 'CRISIL Liquid Fund AI Index',
    fundManager: 'R. Arun',
    investmentObjective: 'To provide investors with a high level of liquidity with reasonable returns.',
    exitLoad: 'Graded exit load up to 7 days',
    mfapiSchemeCode: 119364,
    plans: [
      {
        id: 'PLAN-SBI-LIQUID-DG',
        isin: 'INF200K01QI0',
        rtaIdentifier: 'SBILIQUIDG',
        name: 'SBI Liquid Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119364,
        nav: 3456.78,
        dayChange: 0.52,
        return1m: 0.5,
        return3m: 1.6,
        return6m: 3.2,
        return1y: 6.5,
        return3y: 5.8,
        return5y: 5.5,
        riskRating: 1,
        fundRating: 5,
        expenseRatio: 0.18,
        aum: 78654,
        volatility: 0.2,
        sharpeRatio: 2.5,
      },
    ],
  },
  {
    id: 'SCH-HDFC-CORP',
    providerId: 'AMC-HDFC',
    name: 'HDFC Corporate Bond Fund',
    categoryId: 'L3-CORPORATE_BOND',
    subCategory: 'Corporate Bond',
    benchmark: 'CRISIL Corporate Bond Fund AIII Index',
    fundManager: 'Shobhit Mehrotra',
    investmentObjective: 'To generate income through investments in high quality corporate bonds.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 119237,
    plans: [
      {
        id: 'PLAN-HDFC-CORP-DG',
        isin: 'INF179K01WW3',
        rtaIdentifier: 'HDFCCORPDG',
        name: 'HDFC Corporate Bond Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119237,
        nav: 28.34,
        dayChange: 0.02,
        return1m: 0.6,
        return3m: 1.8,
        return6m: 3.6,
        return1y: 7.2,
        return3y: 6.8,
        return5y: 7.5,
        riskRating: 2,
        fundRating: 4,
        expenseRatio: 0.38,
        aum: 32456,
        volatility: 1.2,
        sharpeRatio: 1.8,
      },
    ],
  },
  {
    id: 'SCH-ICICI-CORP',
    providerId: 'AMC-ICICI',
    name: 'ICICI Prudential Corporate Bond Fund',
    categoryId: 'L3-CORPORATE_BOND',
    subCategory: 'Corporate Bond',
    benchmark: 'CRISIL Corporate Bond Fund AIII Index',
    fundManager: 'Manish Banthia',
    investmentObjective: 'To generate income through investments predominantly in AA+ and above rated corporate bonds.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 119238,
    plans: [
      {
        id: 'PLAN-ICICI-CORP-DG',
        isin: 'INF109K01PV9',
        rtaIdentifier: 'ICICICORPDG',
        name: 'ICICI Prudential Corporate Bond Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119238,
        nav: 26.78,
        dayChange: 0.02,
        return1m: 0.55,
        return3m: 1.7,
        return6m: 3.4,
        return1y: 6.9,
        return3y: 6.5,
        return5y: 7.2,
        riskRating: 2,
        fundRating: 4,
        expenseRatio: 0.35,
        aum: 28765,
        volatility: 1.1,
        sharpeRatio: 1.75,
      },
    ],
  },
  {
    id: 'SCH-AXIS-SHORT',
    providerId: 'AMC-AXIS',
    name: 'Axis Short Term Fund',
    categoryId: 'L3-SHORT_DURATION',
    subCategory: 'Short Duration',
    benchmark: 'CRISIL Short-Term Bond Fund AI',
    fundManager: 'Devang Shah',
    investmentObjective: 'To generate stable returns by investing in a portfolio of short duration debt and money market instruments.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 120520,
    plans: [
      {
        id: 'PLAN-AXIS-SHORT-DG',
        isin: 'INF846K01EE3',
        rtaIdentifier: 'AXISSHORTDG',
        name: 'Axis Short Term Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120520,
        nav: 28.92,
        dayChange: 0.02,
        return1m: 0.6,
        return3m: 1.8,
        return6m: 3.5,
        return1y: 7.0,
        return3y: 6.5,
        return5y: 7.0,
        riskRating: 2,
        fundRating: 4,
        expenseRatio: 0.32,
        aum: 8765,
        volatility: 0.9,
        sharpeRatio: 1.9,
      },
    ],
  },
  {
    id: 'SCH-KOTAK-GILT',
    providerId: 'AMC-KOTAK',
    name: 'Kotak Gilt Fund',
    categoryId: 'L3-GILT',
    subCategory: 'Gilt',
    benchmark: 'CRISIL Dynamic Gilt Index',
    fundManager: 'Deepak Agrawal',
    investmentObjective: 'To generate returns through investments in government securities.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 118821,
    plans: [
      {
        id: 'PLAN-KOTAK-GILT-DG',
        isin: 'INF174K01FN7',
        rtaIdentifier: 'KOTAKGILTDG',
        name: 'Kotak Gilt Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118821,
        nav: 92.45,
        dayChange: 0.08,
        return1m: 0.7,
        return3m: 2.0,
        return6m: 4.0,
        return1y: 8.2,
        return3y: 7.5,
        return5y: 8.0,
        riskRating: 2,
        fundRating: 4,
        expenseRatio: 0.45,
        aum: 2345,
        volatility: 2.5,
        sharpeRatio: 1.5,
      },
    ],
  },
  {
    id: 'SCH-HDFC-MONEY',
    providerId: 'AMC-HDFC',
    name: 'HDFC Money Market Fund',
    categoryId: 'L3-MONEY_MARKET',
    subCategory: 'Money Market',
    benchmark: 'CRISIL Money Market Index',
    fundManager: 'Anil Bamboli',
    investmentObjective: 'To generate regular income through investment in a portfolio comprising substantially of money market instruments.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 118776,
    plans: [
      {
        id: 'PLAN-HDFC-MONEY-DG',
        isin: 'INF179K01WU7',
        rtaIdentifier: 'HDFCMONDG',
        name: 'HDFC Money Market Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118776,
        nav: 5123.45,
        dayChange: 0.78,
        return1m: 0.55,
        return3m: 1.65,
        return6m: 3.3,
        return1y: 6.7,
        return3y: 6.0,
        return5y: 5.8,
        riskRating: 1,
        fundRating: 5,
        expenseRatio: 0.22,
        aum: 15678,
        volatility: 0.3,
        sharpeRatio: 2.2,
      },
    ],
  },

  // =============================================
  // HYBRID FUNDS (4 schemes)
  // =============================================
  {
    id: 'SCH-HDFC-BAF',
    providerId: 'AMC-HDFC',
    name: 'HDFC Balanced Advantage Fund',
    categoryId: 'L3-DYNAMIC_ALLOCATION',
    subCategory: 'Balanced Advantage / Dynamic Asset Allocation',
    benchmark: 'CRISIL Hybrid 35+65 - Aggressive Index',
    fundManager: 'Prashant Jain',
    investmentObjective: 'To generate long-term capital appreciation/income through dynamic asset allocation between equity and debt instruments.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 118834,
    plans: [
      {
        id: 'PLAN-HDFC-BAF-DG',
        isin: 'INF179K01WI2',
        rtaIdentifier: 'HDFCBAFDG',
        name: 'HDFC Balanced Advantage Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118834,
        nav: 45.67,
        dayChange: 0.32,
        return1m: 1.5,
        return3m: 4.2,
        return6m: 9.5,
        return1y: 14.5,
        return3y: 12.2,
        return5y: 13.5,
        riskRating: 3,
        fundRating: 5,
        expenseRatio: 0.85,
        aum: 62345,
        volatility: 10.2,
        sharpeRatio: 1.15,
      },
    ],
  },
  {
    id: 'SCH-ICICI-BAF',
    providerId: 'AMC-ICICI',
    name: 'ICICI Prudential Balanced Advantage Fund',
    categoryId: 'L3-DYNAMIC_ALLOCATION',
    subCategory: 'Balanced Advantage / Dynamic Asset Allocation',
    benchmark: 'CRISIL Hybrid 35+65 - Aggressive Index',
    fundManager: 'Sankaran Naren',
    investmentObjective: 'To generate long-term capital appreciation and current income through a dynamic mix of equity and debt instruments.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 125492,
    plans: [
      {
        id: 'PLAN-ICICI-BAF-DG',
        isin: 'INF109K01P83',
        rtaIdentifier: 'ICICIBAFDG',
        name: 'ICICI Prudential Balanced Advantage Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 125492,
        nav: 58.34,
        dayChange: 0.42,
        return1m: 1.6,
        return3m: 4.5,
        return6m: 10.0,
        return1y: 15.2,
        return3y: 12.8,
        return5y: 14.0,
        riskRating: 3,
        fundRating: 5,
        expenseRatio: 1.02,
        aum: 55678,
        volatility: 10.5,
        sharpeRatio: 1.18,
      },
    ],
  },
  {
    id: 'SCH-KOTAK-HYBRID',
    providerId: 'AMC-KOTAK',
    name: 'Kotak Equity Hybrid Fund',
    categoryId: 'L3-AGGRESSIVE_HYBRID',
    subCategory: 'Aggressive Hybrid',
    benchmark: 'CRISIL Hybrid 35+65 - Aggressive Index',
    fundManager: 'Harsha Upadhyaya',
    investmentObjective: 'To generate long-term capital appreciation and current income from a combined portfolio of equity and fixed income securities.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 120530,
    plans: [
      {
        id: 'PLAN-KOTAK-HYBRID-DG',
        isin: 'INF174K01FM9',
        rtaIdentifier: 'KOTAKHYBDG',
        name: 'Kotak Equity Hybrid Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120530,
        nav: 52.78,
        dayChange: 0.38,
        return1m: 1.7,
        return3m: 4.8,
        return6m: 10.5,
        return1y: 16.0,
        return3y: 13.5,
        return5y: 14.8,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.68,
        aum: 6789,
        volatility: 11.2,
        sharpeRatio: 1.22,
      },
    ],
  },
  {
    id: 'SCH-SBI-EQHYB',
    providerId: 'AMC-SBI',
    name: 'SBI Equity Hybrid Fund',
    categoryId: 'L3-AGGRESSIVE_HYBRID',
    subCategory: 'Aggressive Hybrid',
    benchmark: 'CRISIL Hybrid 35+65 - Aggressive Index',
    fundManager: 'Dinesh Ahuja',
    investmentObjective: 'To generate long term capital growth with reasonable income from a portfolio comprising mix of equity & equity related instruments and fixed income investments.',
    exitLoad: '1% if redeemed within 1 year',
    mfapiSchemeCode: 119714,
    plans: [
      {
        id: 'PLAN-SBI-EQHYB-DG',
        isin: 'INF200K01QH2',
        rtaIdentifier: 'SBIEQHYBDG',
        name: 'SBI Equity Hybrid Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 119714,
        nav: 245.67,
        dayChange: 1.78,
        return1m: 1.8,
        return3m: 5.0,
        return6m: 11.0,
        return1y: 16.8,
        return3y: 14.2,
        return5y: 15.5,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.82,
        aum: 58765,
        volatility: 11.5,
        sharpeRatio: 1.20,
      },
    ],
  },

  // =============================================
  // INDEX FUNDS (4 schemes)
  // =============================================
  {
    id: 'SCH-UTI-NIFTY50',
    providerId: 'AMC-UTI',
    name: 'UTI Nifty 50 Index Fund',
    categoryId: 'L3-INDEX',
    subCategory: 'Index - Nifty 50',
    benchmark: 'NIFTY 50 TRI',
    fundManager: 'Sharwan Kumar Goyal',
    investmentObjective: 'To provide returns that closely correspond to the returns generated by Nifty 50 Index.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 120620,
    plans: [
      {
        id: 'PLAN-UTI-NIFTY50-DG',
        isin: 'INF789F01DH2',
        rtaIdentifier: 'UTINIFTY50DG',
        name: 'UTI Nifty 50 Index Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 120620,
        nav: 148.92,
        dayChange: 1.18,
        return1m: 1.8,
        return3m: 5.2,
        return6m: 11.5,
        return1y: 16.5,
        return3y: 14.0,
        return5y: 15.2,
        riskRating: 4,
        fundRating: 5,
        expenseRatio: 0.10,
        aum: 15678,
        volatility: 13.5,
        sharpeRatio: 1.05,
      },
    ],
  },
  {
    id: 'SCH-MOTILAL-NIFTY50',
    providerId: 'AMC-MOTILAL',
    name: 'Motilal Oswal Nifty 50 Index Fund',
    categoryId: 'L3-INDEX',
    subCategory: 'Index - Nifty 50',
    benchmark: 'NIFTY 50 TRI',
    fundManager: 'Swapnil Mayekar',
    investmentObjective: 'To provide investment returns closely corresponding to the total returns of the securities as represented by the Nifty 50 Index.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 145646,
    plans: [
      {
        id: 'PLAN-MOTILAL-NIFTY50-DG',
        isin: 'INF247L01AF2',
        rtaIdentifier: 'MOTILNIFTY50DG',
        name: 'Motilal Oswal Nifty 50 Index Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 145646,
        nav: 21.45,
        dayChange: 0.17,
        return1m: 1.75,
        return3m: 5.1,
        return6m: 11.3,
        return1y: 16.2,
        return3y: 13.8,
        return5y: 15.0,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.06,
        aum: 3456,
        volatility: 13.5,
        sharpeRatio: 1.03,
      },
    ],
  },
  {
    id: 'SCH-HDFC-SENSEX',
    providerId: 'AMC-HDFC',
    name: 'HDFC Index Fund - Sensex Plan',
    categoryId: 'L3-INDEX',
    subCategory: 'Index - Sensex',
    benchmark: 'S&P BSE SENSEX TRI',
    fundManager: 'Krishan Kumar Daga',
    investmentObjective: 'To generate returns that are commensurate with the performance of S&P BSE Sensex.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 118727,
    plans: [
      {
        id: 'PLAN-HDFC-SENSEX-DG',
        isin: 'INF179K01WR3',
        rtaIdentifier: 'HDFCSENSEXDG',
        name: 'HDFC Index Fund - Sensex Plan - Direct - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 118727,
        nav: 678.92,
        dayChange: 5.42,
        return1m: 1.7,
        return3m: 5.0,
        return6m: 11.0,
        return1y: 15.8,
        return3y: 13.5,
        return5y: 14.8,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.20,
        aum: 6789,
        volatility: 13.2,
        sharpeRatio: 1.02,
      },
    ],
  },
  {
    id: 'SCH-NAVI-NIFTY50',
    providerId: 'AMC-UTI', // Using UTI as placeholder since we don't have Navi
    name: 'Navi Nifty 50 Index Fund',
    categoryId: 'L3-INDEX',
    subCategory: 'Index - Nifty 50',
    benchmark: 'NIFTY 50 TRI',
    fundManager: 'Index Fund Manager',
    investmentObjective: 'To provide investment returns closely corresponding to the returns of Nifty 50 Index.',
    exitLoad: 'Nil',
    mfapiSchemeCode: 149044,
    plans: [
      {
        id: 'PLAN-NAVI-NIFTY50-DG',
        isin: 'INF959L01EX6',
        rtaIdentifier: 'NAVINIFTY50DG',
        name: 'Navi Nifty 50 Index Fund - Direct Plan - Growth',
        plan: 'direct',
        option: 'growth',
        mfapiSchemeCode: 149044,
        nav: 12.85,
        dayChange: 0.10,
        return1m: 1.78,
        return3m: 5.15,
        return6m: 11.4,
        return1y: 16.4,
        return3y: 13.9,
        return5y: 15.1,
        riskRating: 4,
        fundRating: 4,
        expenseRatio: 0.05,
        aum: 456,
        volatility: 13.5,
        sharpeRatio: 1.04,
      },
    ],
  },
];

// Add lockin property to schemes that have it
const schemesWithLockin: Record<string, number> = {
  'SCH-AXIS-ELSS': 1095,
  'SCH-MIRAE-ELSS': 1095,
  'SCH-DSP-ELSS': 1095,
  'SCH-QUANT-ELSS': 1095,
};

// =============================================
// SEED FUNCTIONS
// =============================================

async function seedProviders() {
  console.log('🏢 Seeding providers (AMCs)...');

  for (const provider of PROVIDERS) {
    await prisma.provider.upsert({
      where: { id: provider.id },
      update: {
        name: provider.name,
        shortName: provider.shortName,
        sebiRegNo: provider.sebiRegNo,
        isActive: true,
      },
      create: {
        id: provider.id,
        name: provider.name,
        shortName: provider.shortName,
        sebiRegNo: provider.sebiRegNo,
        isActive: true,
      },
    });
  }

  console.log(`  ✓ ${PROVIDERS.length} providers seeded`);
}

async function seedSchemes() {
  console.log('📊 Seeding schemes...');

  for (const scheme of SCHEMES) {
    // Create/update scheme
    await prisma.scheme.upsert({
      where: { id: scheme.id },
      update: {
        name: scheme.name,
        categoryId: scheme.categoryId,
        subCategory: scheme.subCategory,
        benchmark: scheme.benchmark,
        fundManager: scheme.fundManager,
        investmentObjective: scheme.investmentObjective,
        exitLoad: scheme.exitLoad,
        lockinPeriod: schemesWithLockin[scheme.id] || null,
        mfapiSchemeCode: scheme.mfapiSchemeCode,
        status: 'active',
      },
      create: {
        id: scheme.id,
        providerId: scheme.providerId,
        name: scheme.name,
        categoryId: scheme.categoryId,
        subCategory: scheme.subCategory,
        benchmark: scheme.benchmark,
        fundManager: scheme.fundManager,
        investmentObjective: scheme.investmentObjective,
        exitLoad: scheme.exitLoad,
        lockinPeriod: schemesWithLockin[scheme.id] || null,
        mfapiSchemeCode: scheme.mfapiSchemeCode,
        status: 'active',
      },
    });

    // Create/update scheme plans
    for (const plan of scheme.plans) {
      await prisma.schemePlan.upsert({
        where: { id: plan.id },
        update: {
          isin: plan.isin,
          rtaIdentifier: plan.rtaIdentifier,
          amfiIdentifier: plan.amfiIdentifier,
          name: plan.name,
          plan: plan.plan,
          option: plan.option,
          mfapiSchemeCode: plan.mfapiSchemeCode,
          purchaseAllowed: true,
          redemptionAllowed: true,
          sipAllowed: true,
          switchInAllowed: true,
          switchOutAllowed: true,
          status: 'active',
        },
        create: {
          id: plan.id,
          schemeId: scheme.id,
          isin: plan.isin,
          rtaIdentifier: plan.rtaIdentifier,
          amfiIdentifier: plan.amfiIdentifier,
          name: plan.name,
          plan: plan.plan,
          option: plan.option,
          mfapiSchemeCode: plan.mfapiSchemeCode,
          purchaseAllowed: true,
          redemptionAllowed: true,
          sipAllowed: true,
          switchInAllowed: true,
          switchOutAllowed: true,
          status: 'active',
        },
      });

      // Create/update NAV
      const today = new Date();
      await prisma.schemePlanNav.upsert({
        where: { schemePlanId: plan.id },
        update: {
          navDate: today,
          nav: plan.nav,
          dayChange: plan.dayChange,
          dayChangePct: (plan.dayChange / (plan.nav - plan.dayChange)) * 100,
        },
        create: {
          schemePlanId: plan.id,
          navDate: today,
          nav: plan.nav,
          dayChange: plan.dayChange,
          dayChangePct: (plan.dayChange / (plan.nav - plan.dayChange)) * 100,
        },
      });

      // Create/update metrics
      await prisma.schemePlanMetrics.upsert({
        where: { schemePlanId: plan.id },
        update: {
          return1m: plan.return1m,
          return3m: plan.return3m,
          return6m: plan.return6m,
          return1y: plan.return1y,
          return3y: plan.return3y,
          return5y: plan.return5y,
          riskRating: plan.riskRating,
          fundRating: plan.fundRating,
          expenseRatio: plan.expenseRatio,
          aum: plan.aum,
          aumDate: today,
          volatility: plan.volatility,
          sharpeRatio: plan.sharpeRatio,
        },
        create: {
          schemePlanId: plan.id,
          return1m: plan.return1m,
          return3m: plan.return3m,
          return6m: plan.return6m,
          return1y: plan.return1y,
          return3y: plan.return3y,
          return5y: plan.return5y,
          riskRating: plan.riskRating,
          fundRating: plan.fundRating,
          expenseRatio: plan.expenseRatio,
          aum: plan.aum,
          aumDate: today,
          volatility: plan.volatility,
          sharpeRatio: plan.sharpeRatio,
        },
      });
    }
  }

  const totalPlans = SCHEMES.reduce((sum, s) => sum + s.plans.length, 0);
  console.log(`  ✓ ${SCHEMES.length} schemes with ${totalPlans} plans seeded`);
}

async function main() {
  console.log('🌱 Seeding fund data...\n');

  await seedProviders();
  await seedSchemes();

  // Print summary
  const providerCount = await prisma.provider.count();
  const schemeCount = await prisma.scheme.count();
  const planCount = await prisma.schemePlan.count();
  const navCount = await prisma.schemePlanNav.count();
  const metricsCount = await prisma.schemePlanMetrics.count();

  console.log('\n✅ Fund seeding completed!');
  console.log(`   Providers: ${providerCount}`);
  console.log(`   Schemes: ${schemeCount}`);
  console.log(`   Plans: ${planCount}`);
  console.log(`   NAV records: ${navCount}`);
  console.log(`   Metrics records: ${metricsCount}`);
}

main()
  .catch((e) => {
    console.error('❌ Fund seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
