export const BSE_ERROR_CODES: Record<string, string> = {
  '100': 'Success',
  '101': 'Invalid User ID',
  '102': 'Invalid Member ID',
  '103': 'Invalid Password',
  '104': 'Session expired',
  '105': 'Invalid Pass Key',
  '106': 'Invalid Client Code',
  '107': 'Client not registered with BSE',
  '108': 'Invalid Scheme Code',
  '109': 'Scheme not available for transaction',
  '110': 'Amount below minimum',
  '111': 'Amount above maximum',
  '112': 'Invalid Folio Number',
  '113': 'Units not available for redemption',
  '114': 'Order already cancelled',
  '115': 'Order modification not allowed',
  '116': 'Invalid Transaction Number',
  '117': 'Duplicate Order',
  '118': 'Invalid Date format',
  '119': 'Invalid Frequency',
  '120': 'Mandate not approved',
  '121': 'Mandate expired',
  '122': 'Insufficient mandate amount',
  '123': 'Payment failed',
  '124': 'Payment timeout',
  '125': 'Invalid Bank Code',
  '126': 'Bank not supported for payment mode',
  '127': 'FATCA not uploaded',
  '128': 'CKYC not verified',
  '129': 'KYC not completed',
  '130': 'Nominee details missing',
  '131': 'Invalid ARN',
  '132': 'Invalid EUIN',
  '133': 'File upload failed',
  '134': 'Invalid file format',
  '135': 'File size exceeds limit',
  '200': 'General processing error',
  '201': 'BSE system unavailable',
  '202': 'Request timeout',
}

export function getBseErrorMessage(code: string): string {
  return BSE_ERROR_CODES[code] || `Unknown BSE error (code: ${code})`
}
