name: SparrowInvestFA
options:
  bundleIdPrefix: com.sparrowinvest
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_PREVIEWS: YES

targets:
  SparrowInvestFA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SparrowInvestFA
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: SparrowInvestFA/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sparrowinvest.fa
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    info:
      path: SparrowInvestFA/Resources/Info.plist
      properties:
        CFBundleDisplayName: "Sparrow Invest FA"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

schemes:
  SparrowInvestFA:
    build:
      targets:
        SparrowInvestFA: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
